stages:
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'

image: quay.io/buildah/stable

# before_script:
#   - buildah login -u "$QUAY_USER" -p "$QUAY_PASSWORD" quay.io

variables:
  QUAY_USER: $QUAY_USER
  QUAY_PASSWORD: $QUAY_PASSWORD
  REGISTRY: quay.io
  IMAGE_NAME: quay.io/assemble/backstage

build-and-push-image:
  tags: 
  - backstage
  stage: build
  # script:
  #   - buildah bud -t quay.io/assemble/backstage:latest .
  #   - buildah push quay.io/assemble/backstage:latest
  # when: manual

  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${QUAY_USER}" "${QUAY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_NAME}:${CI_COMMIT_TAG}"  
  rules:
    - if: $CI_COMMIT_TAG      
      