stages:
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'



# before_script:
#   - buildah login -u "$QUAY_USER" -p "$QUAY_PASSWORD" quay.io

variables:
  QUAY_USER: $QUAY_USER
  QUAY_PASSWORD: $QUAY_PASSWORD
  REGISTRY: quay.io
  IMAGE_NAME: quay.io/assemble/backstage

build-and-push-image:
  tags: 
  - backstage
  stage: build
  script:
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${QUAY_USER}" "${QUAY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > ./config.json
    #- buildah login -u "${$QUAY_USER}" -p "${QUAY_PASSWORD}" quay.io
    - buildah bud -t ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} .
    - buildah push --auth ./config.json ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}
  image: 
    name: registry.redhat.io/rhel8/buildah:8.6

  # image:
  #   name: gcr.io/kaniko-project/executor:debug
  #   entrypoint: [""]
  # script:
  #   - mkdir -p /kaniko/.docker
  #   - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${QUAY_USER}" "${QUAY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  #   - >-
  #     /kaniko/executor
  #     --context "${CI_PROJECT_DIR}"
  #     --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
  #     --destination "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"      
      