stages:
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: quay.io/buildah/stable

before_script:
  - buildah login -u "$QUAY_USER" -p "$QUAY_PASSWORD" quay.io

build-and-push-image:
  tags: 
  - backstage
  stage: build
  script:
    - buildah bud -t quay.io/assemble/backstage:latest .
    - buildah push quay.io/assemble/backstage:latest
  when: manual