apiVersion: v1
kind: Secret
metadata:
  name: quay-push-secret
  labels:
    {{- include "backstage-ci.labels" . | nindent 4 }}  
stringData:
  .dockerconfigjson: |
    {"auths":{"quay.io":{"username":"{{ .Values.quay.username }}","password":"{{ .Values.quay.password }}","email":"{{ .Values.quay.username }}@example.com","auth":"{{ list .Values.quay.username ":" .Values.quay.password | join "" | b64enc }}"}}}
type: kubernetes.io/dockerconfigjson